# Generated by Django 5.2.6 on 2026-01-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_twibbleuser_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="twibbleuser",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("system", "System Default"),
                ],
                default="system",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="twibbleuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default-avatar.jpg",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
