# Generated by Django 6.0.1 on 2026-01-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_twibbleuser_theme_alter_twibbleuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twibbleuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='twibbleuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='twibbleuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
