# Generated by Django 6.0.1 on 2026-01-17 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_twibbleuser_first_name_and_more"),
    ]

    operations = []
