# Generated by Django 6.0.1 on 2026-01-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_migrate_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twibbleuser",
            name="display_name",
            field=models.CharField(max_length=50),
        ),
    ]
