# Generated by Django 6.0.1 on 2026-02-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_twibbleuser_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twibbleuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="twibbleuser",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "فاتح"),
                    ("dark", "داكن"),
                    ("system", "افتراضي النظام"),
                ],
                default="system",
                max_length=10,
            ),
        ),
    ]
