# Generated by Django 6.0.1 on 2026-01-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweet_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
