# Generated by Django 6.0.1 on 2026-01-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_tweet_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
