# Generated by Django 6.0.1 on 2026-01-19 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_tweet_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='parent_tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tweets.tweet'),
        ),
    ]
