# Generated by Django 6.0.1 on 2026-01-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0007_tweet_parent_tweet"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tweet_images/"),
        ),
    ]
