# Generated by Django 6.0.1 on 2026-01-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_tag_tweet_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
