# Generated by Django 6.0.1 on 2026-01-23 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0010_alter_tag_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="bookmarks",
            field=models.ManyToManyField(
                blank=True,
                related_name="bookmarked_tweets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
